### ISSUE TITLE
send_message broken?

### ISSUE THREAD

**Issue by amaierhofer** [mailboxer/mailboxer#77]
Hi, 

after an upgrade to 0.0.8 the send_message method appears to be broken, please clarify .. 

```
[8] pry(main)> foo.send_message(bar, 'foo', '123') 
NoMethodError: undefined method `is_read=' for #<Receipt:0x00000008c9c0e0>
from /home/ama/.rvm/gems/ruby-1.9.3-p125@global/gems/activemodel-3.2.6/lib/active_model/attribute_methods.rb:407:in `method_missing'
[9] pry(main)> wtf?
Exception: NoMethodError: undefined method `is_read=' for #<Receipt:0x00000008c9c0e0>
--
0: /home/ama/.rvm/gems/ruby-1.9.3-p125@global/gems/activemodel-3.2.6/lib/active_model/attribute_methods.rb:407:in `method_missing'
1: /home/ama/.rvm/gems/ruby-1.9.3-p125@global/gems/activerecord-3.2.6/lib/active_record/attribute_methods.rb:149:in `method_missing'
2: /home/ama/.rvm/gems/ruby-1.9.3-p125@sf_rails/gems/mailboxer-0.8.0/app/models/message.rb:33:in `block in deliver'
3: /home/ama/.rvm/gems/ruby-1.9.3-p125@sf_rails/gems/mailboxer-0.8.0/app/models/message.rb:30:in `each'
4: /home/ama/.rvm/gems/ruby-1.9.3-p125@sf_rails/gems/mailboxer-0.8.0/app/models/message.rb:30:in `deliver'
5: /home/ama/.rvm/gems/ruby-1.9.3-p125@sf_rails/gems/mailboxer-0.8.0/lib/mailboxer/models/messageable.rb:56:in `send_message'
6: (pry):5:in `<main>'
7: /home/ama/.rvm/gems/ruby-1.9.3-p125@global/gems/pry-0.9.10/lib/pry/pry_instance.rb:275:in `eval'
8: /home/ama/.rvm/gems/ruby-1.9.3-p125@global/gems/pry-0.9.10/lib/pry/pry_instance.rb:275:in `re'
9: /home/ama/.rvm/gems/ruby-1.9.3-p125@global/gems/pry-0.9.10/lib/pry/pry_instance.rb:251:in `rep'
```
